const DIFFICULTY = 3; 
const MINE_RATE = 3000;
const INITIAL_BALANCE = 500;
const MINING_REWARD = 50;
const TRANSACTION_FEE = 1;

module.exports = { DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWARD, TRANSACTION_FEE };